<?php
/**
 * Created by PhpStorm.
 * User: Max
 * Date: 11.09.14
 * Time: 18:15
 */

if (function_exists("register_field_group")) {
    register_field_group(array(
        'id' => 'acf_golosyvannya',
        'title' => 'Голосування',
        'fields' => array(
            array(
                'key' => 'field_54059ab243e9a',
                'label' => 'Активне голосування',
                'name' => 'active_voting',
                'type' => 'taxonomy',
                'required' => 1,
                'taxonomy' => 'voting',
                'field_type' => 'select',
                'allow_null' => 1,
                'load_save_terms' => 0,
                'return_format' => 'id',
                'multiple' => 0,
            ),
            array(
                'key' => 'field_54059b2b7f069n',
                'label' => 'Включить заглушку?',
                'name' => 'is_placeholder',
                'type' => 'true_false',
                'message' => '',
                'default_value' => 0,
            ),
            array(
                'key' => 'field_54059b2b7f069n2',
                'label' => 'Воскресный выпуск',
                'name' => 'is_special_episode',
                'type' => 'true_false',
                'message' => '',
                'default_value' => 0,
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'acf-options',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array(
            'position' => 'normal',
            'layout' => 'no_box',
            'hide_on_screen' => array(),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array(
        'id' => 'acf_polya_dlya_zapytannya',
        'title' => 'Поля для запитання',
        'fields' => array(
            array(
                'key' => 'field_540cb6dfe7ce0',
                'label' => 'До кого питання',
                'name' => 'question_to',
                'type' => 'post_object',
                'instructions' => 'Залиште поле пустим якщо питання до всiх учасникiв',
                'post_type' => array(
                    0 => 'contestant',
                ),
                'taxonomy' => array(
                    0 => 'all',
                ),
                'allow_null' => 1,
                'multiple' => 0,
            ),
            array(
                'key' => 'field_540cb4447eec7',
                'label' => 'Мiсто',
                'name' => 'city',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'none',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_540cc5fef5575',
                'label' => 'Епізод',
                'name' => 'episod',
                'type' => 'taxonomy',
                'instructions' => 'До якого епізоду належить запитання',
                'taxonomy' => 'voting',
                'field_type' => 'select',
                'allow_null' => 1,
                'load_save_terms' => 0,
                'return_format' => 'id',
                'multiple' => 0,
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'question',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array(
            'position' => 'normal',
            'layout' => 'no_box',
            'hide_on_screen' => array(),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array(
        'id' => 'acf_uchasnyk',
        'title' => 'Учасник',
        'fields' => array(
            array(
                'key' => 'field_540cbbf4ce493',
                'label' => 'Ім\'я у родовому відмінку',
                'name' => 'name_to',
                'type' => 'text',
                'instructions' => 'Питання до ...',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'none',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_540cc41633df1',
                'label' => 'Звання',
                'name' => 'occupation',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'none',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_541ad439f6443',
                'label' => 'Порядковий номер',
                'name' => 'sort_order',
                'type' => 'number',
                'required' => 1,
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'none',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_540cc41633df1_',
                'label' => 'Результати голосування (%)',
                'name' => 'votes_results',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'none',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_541c74eadf3d1',
                'label' => 'Відео ID',
                'name' => 'video',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'none',
                'maxlength' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'contestant',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array(
            'position' => 'normal',
            'layout' => 'no_box',
            'hide_on_screen' => array(),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array(
        'id' => 'acf_moment',
        'title' => 'Момент',
        'fields' => array(
            array(
                'key' => 'field_541c76861892c',
                'label' => 'Епізод',
                'name' => 'episode',
                'type' => 'taxonomy',
                'taxonomy' => 'voting',
                'field_type' => 'select',
                'required' => 1,
                'allow_null' => 1,
                'load_save_terms' => 0,
                'return_format' => 'id',
                'multiple' => 0,
            ),
            array(
                'key' => 'field_542001e4128af',
                'label' => 'Короткий зміст',
                'name' => 'description',
                'type' => 'textarea',
                'required' => 1,
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'formatting' => 'br',
            ),
            array(
                'key' => 'field_541c74eadf3d1',
                'label' => 'Відео ID',
                'name' => 'video',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'none',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_541c74eadf3d2',
                'label' => 'OVVA відео ID',
                'name' => 'video_ovva',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'none',
                'maxlength' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'moments',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array(
            'position' => 'normal',
            'layout' => 'no_box',
            'hide_on_screen' => array(),
        ),
        'menu_order' => 0,
    ));
}

if (function_exists("register_field_group")) {
    register_field_group(array(
        'id' => 'acf_golosuvannya_2',
        'title' => 'Голосування',
        'fields' => array(
            array(
                'key' => 'field_54218a4d02973',
                'label' => 'Название эфира',
                'instructions' => 'Если 2 темы то используется как первая тема',
                'required' => 1,
                'name' => 'fancy_name',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_54059b2b7f068',
                'label' => 'Этап голосования',
                'instructions' => 'Определяет на каком этапе находится текущее голосование',
                'name' => 'voting_stage',
                'type' => 'select',
                'choices' => array(
                    'before_start' => 'Голосування не почалося (перед ефiром)',
                    'voting' => 'Голосування (пiд час ефiру)',
                    'voting_finished' => 'Голосування завершене (пiсля ефiру)',
                    'voting_results' => 'Голосування завершене + результати (пiсля ефiру)',
                ),
                'message' => '',
                'default_value' => 0,
            ),
            array(
                'key' => 'field_54218a0002972',
                'label' => 'Изображение',
                'instructions' => 'Картинка для архива',
                'name' => 'thumbnail',
                'type' => 'image',
                'save_format' => 'object',
                'preview_size' => 'thumbnail',
                'library' => 'all',
            ),
            array(
                'key' => 'field_54218a7d02974',
                'label' => 'Дата эфира',
                'instructions' => 'Используется в архиве, формат дд.мм.гг',
                'name' => 'date',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_54218ac602975',
                'label' => 'Эксперты',
                'name' => 'experts',
                'type' => 'text',
                'instructions' => 'Список экспертов для архива. Разделять запятыми',
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'formatting' => '',
            ),
            array(
                'key' => 'field_54218ac602975_',
                'label' => 'Гости',
                'required' => 0,
                'name' => 'guests',
                'type' => 'text',
                'instructions' => 'Список гостей для архива. Разделять запятыми',
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'formatting' => '',
            ),
            array(
                'key' => 'field_542265024b131',
                'label' => 'Видео эфира',
                'name' => 'video',
                'type' => 'text',
                'instructions' => 'ID с YouTube',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5421887fd7950',
                'label' => 'Теги эпизода',
                'name' => 'episode_tags',
                'type' => 'text',
                'instructions' => 'Список тегов для архива. Разделять запятыми',
            ),
            array(
                'key' => 'field_5463b1cfd9d31',
                'label' => 'Эфир с опросом',
                'instructions' => 'Когда включено за гостей не голосуют, но появляется опрос',
                'name' => 'is_poll',
                'type' => 'true_false',
                'message' => '',
                'default_value' => 0,
            ),
            array(
                'key' => 'field_5463b204d9d32',
                'label' => 'Вопрос',
                'instructions' => 'Вопрос для первого опроса',
                'name' => 'question',
                'type' => 'text',
                'conditional_logic' => array(
                    'status' => 1,
                    'rules' => array(
                        array(
                            'field' => 'field_5463b1cfd9d31',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'br',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5463b243d9d33',
                'label' => 'Варианты ответов',
                'instructions' => 'Варианты ответов на вопрос. Если в эфире 2 опроса, то ID ответов обоих опросов не должны пересекаться между собой. К примеру: первый опрос - ответы "ID 1 - да, ID 2 - нет", второй опрос - ответы "ID 3 - да, ID 4 - нет". Если не добавлять ответы - опрос показываться не будет',
                'name' => 'answers',
                'type' => 'repeater',
                'required' => 1,
                'conditional_logic' => array(
                    'status' => 1,
                    'rules' => array(
                        array(
                            'field' => 'field_5463b1cfd9d31',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'sub_fields' => array(
                    array(
                        'key' => 'field_5463c9172e87f',
                        'label' => 'ID',
                        'name' => 'id',
                        'type' => 'number',
                        'instructions' => 'Уникальное число',
                        'required' => 1,
                        'column_width' => 10,
                        'default_value' => 1,
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'min' => 1,
                        'max' => '',
                        'step' => 1,
                    ),
                    array(
                        'key' => 'field_5463b27cd9d34',
                        'label' => 'Ответ',
                        'name' => 'answer',
                        'type' => 'text',
                        'required' => 1,
                    ),
                    array(
                        'key' => 'field_5463d4c8b7a46',
                        'label' => 'Результат',
                        'name' => 'result',
                        'type' => 'number',
                        'column_width' => 10,
                        'default_value' => 0,
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '%',
                        'min' => 0,
                        'max' => 100,
                        'step' => 1,
                    ),
                ),
                'row_min' => '',
                'row_limit' => '',
                'layout' => 'table',
                'button_label' => 'Добавить вариант ответа',
            ),
            array(
                'key' => 'field_guestsinstudio',
                'label' => 'Гости',
                'instructions' => 'Если 2 темы, то гости для первой темы',
                'name' => 'guests_in_studio',
                'type' => 'repeater',
                'required' => 1,
                'conditional_logic' => array(
                    'status' => 1,
                    'rules' => array(
                        array(
                            'field' => 'field_5463b1cfd9d31',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'sub_fields' => array(
                    array(
                        'key' => 'field_5463b33cd9123123',
                        'label' => 'ID',
                        'instructions' => 'Уникальное число',
                        'name' => 'id',
                        'type' => 'number',
                        'required' => 1,
                        'column_width' => 5
                    ),
                    array(
                        'key' => 'field_5463b320d9d36',
                        'label' => 'Фото',
                        'name' => 'photo',
                        'type' => 'image',
                        'required' => 1,
                        'column_width' => 10,
                        'save_format' => 'object',
                        'preview_size' => 'thumbnail',
                        'library' => 'all',
                    ),
                    array(
                        'key' => 'field_5463b33cd9d37',
                        'label' => 'Имя',
                        'name' => 'name',
                        'type' => 'text',
                        'required' => 1,
                        'column_width' => '20',
                    ),
                    array(
                        'key' => 'field_5463b33cd9d37_11',
                        'label' => 'Имя в дательном падеже',
                        'instructions' => 'Кому?',
                        'name' => 'name_to',
                        'type' => 'text',
                        'required' => 1,
                        'column_width' => '20',
                    ),
                    array(
                        'key' => 'field_5463c98c2e880',
                        'label' => 'Должность',
                        'name' => 'job',
                        'type' => 'text',
                        'required' => 1,
                        'column_width' => '20',
                    ),
                    array(
                        'key' => 'field_5463b353d9d38',
                        'label' => 'Досье',
                        'name' => 'info',
                        'type' => 'textarea',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => 10,
                        'formatting' => 'br',
                    ),
                ),
                'row_min' => '',
                'layout' => 'table',
                'button_label' => 'Добавить гостя',
            ),
            array(
                'key' => 'field_5463b2d4d9d35',
                'label' => 'Эксперты',
                'name' => 'experts_in_studio',
                'instructions' => 'Если 2 темы, то эксперты для первой темы',
                'type' => 'repeater',
                'required' => 1,
                'conditional_logic' => array(
                    'status' => 1,
                    'rules' => array(
                        array(
                            'field' => 'field_5463b1cfd9d31',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'sub_fields' => array(
                    array(
                        'key' => 'field_5463b320d9d36',
                        'label' => 'Фото',
                        'name' => 'photo',
                        'type' => 'image',
                        'required' => 1,
                        'column_width' => '',
                        'save_format' => 'object',
                        'preview_size' => 'thumbnail',
                        'library' => 'all',
                    ),
                    array(
                        'key' => 'field_5463b33cd9d37',
                        'label' => 'Имя',
                        'name' => 'name',
                        'type' => 'text',
                        'required' => 1,
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'none',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5463c98c2e880',
                        'label' => 'Должность',
                        'name' => 'job',
                        'type' => 'text',
                        'required' => 1,
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'none',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5463b353d9d38',
                        'label' => 'Досье',
                        'name' => 'info',
                        'type' => 'textarea',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => 10,
                        'formatting' => 'br',
                    ),
                ),
                'row_min' => '',
                'layout' => 'table',
                'button_label' => 'Добавить эксперта',
            ),
//-----------------
            array(
                'key' => 'field_5463b1cfd9d31_2',
                'label' => 'Включить вторую тему?',
                'instructions' => 'Когда включено, то добавляется новая секция где можно добавить гостей, экспертов и опрос',
                'name' => 'is_second_subject',
                'type' => 'true_false',
                'message' => '',
                'default_value' => 0,
            ),
            array(
                'key' => 'field_5463b204d9d3_222',
                'label' => 'Вторая тема',
                'instructions' => 'Название второй темы',
                'name' => 'second_subject',
                'type' => 'text',
                'conditional_logic' => array(
                    'status' => 1,
                    'rules' => array(
                        array(
                            'field' => 'field_5463b1cfd9d31_2',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'none',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5463b204d9d32_2',
                'label' => 'Вопрос',
                'instructions' => 'Вопрос для второго опроса',
                'name' => 'second_question',
                'type' => 'text',
                'conditional_logic' => array(
                    'status' => 1,
                    'rules' => array(
                        array(
                            'field' => 'field_5463b1cfd9d31_2',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'br',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5463b243d9d33_2',
                'label' => 'Варианты ответов',
                'instructions' => 'Варианты ответов на вопрос. Если в эфире 2 опроса, то ID ответов обоих опросов не должны пересекаться между собой. К примеру: первый опрос - ответы "ID 1 - да, ID 2 - нет", второй опрос - ответы "ID 3 - да, ID 4 - нет". Если не добавлять ответы - опрос показываться не будет',
                'name' => 'second_answers',
                'type' => 'repeater',
                'conditional_logic' => array(
                    'status' => 1,
                    'rules' => array(
                        array(
                            'field' => 'field_5463b1cfd9d31_2',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'sub_fields' => array(
                    array(
                        'key' => 'field_5463c9172e87f_22',
                        'label' => 'ID',
                        'name' => 'id',
                        'type' => 'number',
                        'instructions' => 'Уникальное число',
                        'required' => 1,
                        'column_width' => 10,
                        'default_value' => 1,
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'min' => 1,
                        'max' => '',
                        'step' => 1,
                    ),
                    array(
                        'key' => 'field_5463b27cd9d34_22',
                        'label' => 'Ответ',
                        'name' => 'answer',
                        'type' => 'text',
                        'required' => 1,
                        'column_width' => 0,
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'none',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5463d4c8b7a46_22',
                        'label' => 'Результат',
                        'name' => 'result',
                        'type' => 'number',
                        'column_width' => 10,
                        'default_value' => 0,
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '%',
                        'min' => 0,
                        'max' => 100,
                        'step' => 1,
                    ),
                ),
                'row_min' => '',
                'row_limit' => '',
                'layout' => 'table',
                'button_label' => 'Добавить вариант ответа',
            ),
            array(
                'key' => 'field_guestsinstudio_2',
                'label' => 'Гости',
                'instructions' => 'Гости для второй темы. Если 2 темы, то ID гостей не должны пересекаться с ID гостей из первой темы',
                'name' => 'second_guests_in_studio',
                'type' => 'repeater',
                'required' => 1,
                'conditional_logic' => array(
                    'status' => 1,
                    'rules' => array(
                        array(
                            'field' => 'field_5463b1cfd9d31_2',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'sub_fields' => array(
                    array(
                        'key' => 'field_5463b33cd91231231',
                        'label' => 'ID',
                        'instructions' => 'Уникальное число',
                        'name' => 'id',
                        'type' => 'number',
                        'required' => 1,
                        'column_width' => '20'
                    ),
                    array(
                        'key' => 'field_5463b320d9d36_22',
                        'label' => 'Фото',
                        'name' => 'photo',
                        'type' => 'image',
                        'required' => 1,
                        'column_width' => '',
                        'save_format' => 'object',
                        'preview_size' => 'thumbnail',
                        'library' => 'all',
                    ),
                    array(
                        'key' => 'field_5463b33cd9d37_22',
                        'label' => 'Имя',
                        'name' => 'name',
                        'type' => 'text',
                        'required' => 1,
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'none',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5463b33cd9d37_221',
                        'label' => 'Имя в дательном падеже',
                        'instructions' => 'Кому?',
                        'name' => 'name_to',
                        'type' => 'text',
                        'required' => 1
                    ),
                    array(
                        'key' => 'field_5463c98c2e880_22',
                        'label' => 'Должность',
                        'name' => 'job',
                        'type' => 'text',
                        'required' => 1
                    ),
                    array(
                        'key' => 'field_5463b353d9d38_22',
                        'label' => 'Досье',
                        'name' => 'info',
                        'type' => 'textarea',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => 10,
                        'formatting' => 'br',
                    ),
                ),
                'row_min' => '',
                'layout' => 'table',
                'button_label' => 'Добавить гостя',
            ),
            array(
                'key' => 'field_5463b2d4d9d35_2',
                'label' => 'Эксперты',
                'instructions' => 'Эксперты для второй темы',
                'name' => 'second_experts_in_studio',
                'type' => 'repeater',
                'required' => 1,
                'conditional_logic' => array(
                    'status' => 1,
                    'rules' => array(
                        array(
                            'field' => 'field_5463b1cfd9d31_2',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'sub_fields' => array(
                    array(
                        'key' => 'field_5463b320d9d36_22',
                        'label' => 'Фото',
                        'name' => 'photo',
                        'type' => 'image',
                        'required' => 1,
                        'column_width' => '',
                        'save_format' => 'object',
                        'preview_size' => 'thumbnail',
                        'library' => 'all',
                    ),
                    array(
                        'key' => 'field_5463b33cd9d37_22',
                        'label' => 'Имя',
                        'name' => 'name',
                        'type' => 'text',
                        'required' => 1,
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'none',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5463c98c2e880_22',
                        'label' => 'Должность',
                        'name' => 'job',
                        'type' => 'text',
                        'required' => 1,
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'none',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5463b353d9d38_22',
                        'label' => 'Досье',
                        'name' => 'info',
                        'type' => 'textarea',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => 10,
                        'formatting' => 'br',
                    ),
                ),
                'row_min' => '',
                'layout' => 'table',
                'button_label' => 'Добавить эксперта',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'ef_taxonomy',
                    'operator' => '==',
                    'value' => 'voting',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array(
            'position' => 'normal',
            'layout' => 'no_box',
            'hide_on_screen' => array(),
        ),
        'menu_order' => 0,
    ));
}
